documentation/src/main/asciidoc/core/manual/en_US/01_getting_started.adoc
=> createCriteriaBuilderFactory takes entityManagerFactory

README.md
=> artifactId for Hibernate integration changed

core/testsuite/src/test/java/com/blazebit/persistence/testsuite/Issue227Test.java
Test case for issue Hibernate integration: CTE seems to break `@Fetch(Subselect)` #227
=> Reproduce issue #227: Hibernate FetchMode.SUBSELECT support

core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue227Test.java
FetchMode.SUBSELECT is correctly fixed, but the problem still occurs for ManyToOne relationships. Probably a similar patch can be applied there. I am investigating the issue but already wanted to share this reproduction test case.
=> FetchMode.SUBSELECT for ManyToOne relationships

integration/hibernate-base/src/main/java/com/blazebit/persistence/impl/hibernate/HibernateExtendedQuerySupport.java
This solved the #336 NPE for me. I am not entirely sure if this adds full support for `@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)` though, as I am not using any EntityViews or CTE's for this particular entity. Is a test case needed for this?
=> Handle UnionSubclassEntityPersister polymorphic issues

website/src/main/jbake/content/index.html
Fixes a few minor English prepositions in your front page
=> fix some english prepositions

.travis.yml, build.sh, integration/spring-data/pom.xml, integration/spring-data/src/main/java/com/blazebit/persistence/impl/springdata/repository/EntityViewRepositoryFactoryBean.java, integration/spring-data/src/main/java/org/springframework/data/repository/core/support/BlazeRepositoryFactoryBeanSupport.java, integration/spring-data/src/main/java/org/springframework/data/repository/core/support/BlazeTransactionalRepositoryFactoryBeanSupport.java, pom.xml
Fixes compatibility of Spring Data Integration for Spring Data 1.11.x.
=> [#406] Upgrade spring data integration to support Spring Boot 1.5.x

core/impl/src/main/java/com/blazebit/persistence/impl/transform/SizeTransformationVisitor.java
Added some comments for clarification to SIZE to COUNT transformation.
#353
=> #353 added some remarks to size to count transformation

documentation/src/main/asciidoc/entity-view/manual/en_US/09_spring_data.adoc, integration/spring-data/src/main/java/com/blazebit/persistence/impl/springdata/repository/EntityViewAwareRepositoryFactory.java, integration/spring-data/src/main/java/com/blazebit/persistence/impl/springdata/repository/EntityViewRepositoryImpl.java, integration/spring-data/src/main/java/com/blazebit/persistence/impl/springdata/repository/EntityViewSpecificationExecutor.java, integration/spring-data/src/main/java/org/springframework/data/jpa/repository/query/FixedJpaCountQueryCreator.java, integration/spring-data/src/main/java/org/springframework/data/jpa/repository/query/FixedJpaQueryCreator.java, integration/spring-data/src/main/java/org/springframework/data/jpa/repository/query/PartTreeEntityViewQuery.java, integration/spring-data/src/test/java/com/blazebit/persistence/impl/springdata/DocumentRepositoryTest.java, integration/spring-data/src/test/java/com/blazebit/persistence/impl/springdata/repository/DocumentRepository.java
Adds support for Spring Data Specifications.
#351
=> #351 Spring Data Specifications

.travis.yml
=> Use OpenJDK7 instead of wrongly relying on OracleJDK7 being the default

core/impl/src/main/java/com/blazebit/persistence/impl/JpaUtils.java
=> #457 - Fixed resolving correct attribute type for unrelated static and JPA reported types

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java
=> #466 - Use entity name as opposed to entity class name in queries

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AnnotationViewMappingReader.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedFlatViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/FlatViewTypeImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImplementor.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewMappingImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewTypeImpl.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/polymorphic/MultiLevelViewInheritanceTest.java
=> Fix for #475

core/impl/src/main/java/com/blazebit/persistence/impl/SubqueryInitiatorFactory.java
=> Fix copying max result in SubqueryInitializer FullQueryBuilder embed, fixes #485

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractModificationCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AliasManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SubqueryTest.java
=> #504 - fixed nested implicit alias allocation

core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/SecondaryTableEntityBase.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/SecondaryTableEntitySub.java, core/testsuite/src/main/resources/META-INF/persistence.xml, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/Issue521Test.java
=> Reproducer for issue #521 (issue not present since Alpha4)

dist/full/pom.xml
The `dist` profile failed for me, these changes may come in handy when we publish a new release.
=> Fixed dist full pom.xml

core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue519Test.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/Issue521Test.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java
This is my attempt of fixing #519 . The reproducer testcase from #523 now passes, but I have a few questions regarding the implementation, and I haven't yet verified whether this approach will compile for all versions of Hibernate.
=>  Support Hibernate Subselect entity (fixes #519)

examples/deltaspike-data-rest/README.md, examples/deltaspike-data-rest/src/main/java/com/blazebit/persistence/examples/deltaspike/data/rest/repository/CatJpaRepository.java, examples/deltaspike-data-rest/src/test/java/com/blazebit/persistence/examples/deltaspike/data/rest/AbstractSampleTest.java, examples/spring-data-rest/pom.xml, examples/spring-data-rest/src/main/java/com/blazebit/persistence/examples/spring/data/rest/Application.java, examples/spring-data-rest/src/main/java/com/blazebit/persistence/examples/spring/data/rest/repository/CatJpaRepository.java, examples/spring-data-rest/src/test/java/com/blazebit/persistence/examples/spring/data/rest/repository/AbstractSampleTest.java, examples/spring-data-rest/src/test/java/com/blazebit/persistence/examples/spring/data/rest/repository/SampleTest.java, examples/spring-data-rest/src/test/resources/logback-test.xml, integration/deltaspike-data/base/src/main/java/com/blazebit/persistence/deltaspike/data/base/handler/AbstractEntityViewAwareRepositoryHandler.java, integration/deltaspike-data/impl-1.7/src/main/java/com/blazebit/persistence/deltaspike/data/impl/handler/EntityViewRepositoryHandler.java, integration/deltaspike-data/impl-1.8/src/main/java/com/blazebit/persistence/deltaspike/data/impl/handler/EntityViewRepositoryHandler.java, integration/entity-view-spring/src/test/resources/logback-test.xml, integration/spring-data/1.x/src/main/java/com/blazebit/persistence/spring/data/impl/repository/BlazePersistenceRepositoryFactory.java, integration/spring-data/2.x/src/main/java/com/blazebit/persistence/spring/data/impl/repository/BlazePersistenceRepositoryFactory.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/EntityViewAwareRepositoryImpl.java, integration/spring-data/testsuite/src/test/resources/logback-test.xml, parent/pom.xml
=> Fix some Spring Data related issue that appear when using normal JpaRepository

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/CollectionAddAllAction.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/ListAddAction.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/ListAddAllAction.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/CorrelatedCollectionBatchTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/CorrelatedCollectionSubselectTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CompositeAttributeFlusher.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/EntityViewAwareRepositoryImpl.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/AbstractSpringTest.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentRepositoryTest.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/config/CustomLocalContainerEntityManagerFactoryBean.java, integration/spring-data/testsuite/src/test/resources/com/blazebit/persistence/spring/data/impl/application-config.xml, integration/spring-data/testsuite/src/test/resources/logging.properties, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/AbstractJpaPersistenceTest.java
Fixes for #560 and small fixes for issues that came up during testing of RC1
#560
=> Fix updatable entity views issue regarding wrong initial state, support different fetch types for updatable attributes, Fix mapped superclass issue

.travis.yml, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedTypedQueryImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/ParameterManager.java, integration/deltaspike-data/testsuite/pom.xml, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate4Integrator.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate43Integrator.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate52Integrator.java, integration/hibernate-5.3/pom.xml, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate53Integrator.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate53MetadataContributor.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate5Integrator.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate60Integrator.java, parent/pom.xml, testsuite-base/hibernate/src/main/java/com/blazebit/persistence/testsuite/base/AbstractPersistenceTest.java, website/src/main/jbake/assets/.htaccess
=> Preparation for Hibernate 5.3

core/impl/pom.xml, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/joinable/JoinableCorrelationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/joinable/model/DocumentJoinableCorrelationView.java, integration/hibernate-base/pom.xml, jpa-criteria/impl/pom.xml, parent/pom.xml
=> [#544] Use proper join alias for correlation result in join fetch correlated mappings

CHANGELOG.md, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/CTESubselectFilteringTest.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/SubselectLoaderUtils.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/SubselectPreparedStatementProxyHandler.java
=> Properly insert CTE params for Subselect fetch with positioned params

core/testsuite/pom.xml, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue545Test.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java, parent/pom.xml
=> [#545] Fallback to default Size if not Sized

core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinNode.java, core/parser/src/main/java/com/blazebit/persistence/parser/PathTargetResolvingExpressionVisitor.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/BookEntity.java, creating-a-release.md, dist/bom/pom.xml, dist/pom.xml, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java, jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/JoinMapKeyEmbeddableTest.java, pom.xml
=> Fix various small issues that were introduced while working on issues for this version

integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/EntityViewAwareRepositoryImpl.java
Adds support for updatable entity views in save/delete repository methods, checking if the instance is a `EntityViewProxy` and calling the EVM update/remove methods.
Fixes #619
=> [#619] Add support for updatable entity views in Spring repository

integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/AbstractPartTreeBlazePersistenceQuery.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/JpaParameters.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentRepositoryTest.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/repository/DocumentRepository.java
Add support for using specifications in Spring Data Repository Query methods.
Should fix #564.
=> [#564] Add support for specifications

core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue666Test.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/InternalQuery.java, website/src/main/jbake/content/documentation.adoc
=>  [#691] Fix support for multi-column attributes where some are formulas

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/RecordingMap.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/mapper/ViewMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/TupleId.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformator/TupleTransformator.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformator/TupleTransformatorFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/AbstractIndexedTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/AbstractNonIndexedTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedSubselectTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/CorrelatedCollectionSubselectTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/CorrelatedSingularSubselectTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/AbstractPluralAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CompositeAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/FusedMapActions.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/IndexedListAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/MapAttributeFlusher.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/collections/entity/simple/PersonForCollections.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/collections/subview/SelectFetchNestedEmptyCollectionsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/collections/subview/model/PersonForCollectionsSelectFetchNestedView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/collections/subview/model/SubviewDocumentSelectFetchView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/collections/subview/model/SubviewPersonForCollectionsSelectFetchView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/convert/view/ConvertViewTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/convert/view/model/DocumentCloneUpdateView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/nestedjoin/JoinableCorrelationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/nestedjoin/model/DocumentNestedJoinView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/nestedjoin/model/PersonNestedJoinSubView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/nestedjoin/model/SimpleDocumentView.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/InternalQuery.java
Fixes #699, Fixes #705, Fixes #706, Fixes #707, Fixes #708, Fixes #709, Fixes #710
=> [#699] Make use of proper mutable attribute count for updatable inheritance type

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/RecordingCollection.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/mapper/ViewMapper.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/simple/EntityViewUpdateSubviewInverseSimpleTest.java
=> [#718] Test and fix for re-add of already contained elements to sets 

core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CTEQueryResultCachingTest.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateExtendedQuerySupport.java
Finally found the time to finish off my PR 😄
=> Support of cachable CTE queries

archetype/spring-boot-sample/src/main/resources/archetype-resources/pom.xml, archetype/spring-data-sample/src/main/resources/archetype-resources/pom.xml, examples/showcase/runner/spring/pom.xml, examples/spring-data-rest/pom.xml, integration/entity-view-spring/pom.xml, integration/spring-data/base/pom.xml, integration/spring-data/rest/pom.xml, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/BlazePersistenceWebConfiguration.java, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/ConversionServiceAutoConfiguration.java, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/KeysetPageableHandlerMethodArgumentResolver.java, integration/spring-data/testsuite/pom.xml, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/AbstractSpringTest.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/AbstractSpringWebMvcTest.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentControllerTest.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentRepositoryTest.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/controller/DocumentController.java, parent/pom.xml
=> [#738] add support for unsorted marker value in Spring Data 2.1.x

integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/HibernateJpqlFunctionAdapter.java
=> [#788] fix HibernateJpqlFunctionAdapter for Hibernate 5.3

integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateExtendedQuerySupport.java
=> [#782] Allow to determine sql alias for insert-select statement

integration/spring-data/1.x/src/main/java/com/blazebit/persistence/spring/data/impl/query/CriteriaQueryParameterBinder.java, integration/spring-data/1.x/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java, integration/spring-data/1.x/src/main/java/com/blazebit/persistence/spring/data/impl/repository/EntityViewAwareRepositoryImpl.java, integration/spring-data/2.0/src/main/java/com/blazebit/persistence/spring/data/impl/query/CriteriaQueryParameterBinder.java, integration/spring-data/2.0/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java, integration/spring-data/2.0/src/main/java/com/blazebit/persistence/spring/data/impl/repository/EntityViewAwareRepositoryImpl.java, integration/spring-data/2.1/src/main/java/com/blazebit/persistence/spring/data/impl/query/CriteriaQueryParameterBinder.java, integration/spring-data/2.1/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java, integration/spring-data/2.1/src/main/java/com/blazebit/persistence/spring/data/impl/repository/EntityViewAwareRepositoryImpl.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/repository/KeysetPageRequest.java, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/KeysetPageableHandlerMethodArgumentResolver.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentControllerTest.java
=> [#795] fix offset parameter in spring data rest integration

core/impl/src/main/java/com/blazebit/persistence/impl/function/cast/CastFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/entity/EntityFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/util/JpqlFunctionUtil.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/JpqlFunctionTest.java, documentation/src/main/asciidoc/core/manual/en_US/18_jpql_functions.adoc, integration/eclipselink/src/main/java/com/blazebit/persistence/integration/eclipselink/function/JpqlFunctionExpressionOperator.java, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/assertion/AssertStatementBuilder.java
=> [#780] extend cast function with optional sql cast type parameter

documentation/src/main/asciidoc/entity-view/manual/en_US/04_mappings.adoc, entity-view/api/src/main/java/com/blazebit/persistence/view/CTEProvider.java, entity-view/api/src/main/java/com/blazebit/persistence/view/With.java, entity-view/api/src/main/java/com/blazebit/persistence/view/metamodel/ManagedViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/CTEProviderFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/PrefixingQueryGenerator.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/SimpleCTEProviderFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AnnotationViewMappingReader.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedFlatViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedViewMapping.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImplementor.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/MetamodelBuildingContext.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/MetamodelBuildingContextImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewMapping.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewMappingImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilder.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedTupleListTransformer.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/WithCTEMappingTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/DocumentOwnersCTE.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/DocumentWithCTE.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/PersonWithPartnerDocument.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/PersonWithPartnerDocumentFullAged.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/PersonWithPartnerDocumentUnderAged.java
=> [#804] CTE support in entity views

.travis.yml, core/api/src/main/java/com/blazebit/persistence/KeysetPage.java, core/api/src/main/java/com/blazebit/persistence/PaginatedCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedTypedQueryImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/builder/object/DelegatingKeysetExtractionObjectBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/builder/object/KeysetExtractionObjectBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/keyset/KeysetPageImpl.java, core/parser/pom.xml, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/QueryResultCachingTest.java, dist/bom/pom.xml, documentation/src/main/asciidoc/entity-view/manual/en_US/04_mappings.adoc, entity-view/api/src/main/java/com/blazebit/persistence/view/CTEProvider.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilder.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/WithCTEMappingTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/DocumentWithCTE.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/PersonWithPartnerDocumentFullAged.java, integration/deltaspike-data/rest/impl/src/main/java/com/blazebit/persistence/deltaspike/data/rest/impl/KeysetPageImpl.java, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/KeysetPageImpl.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/RenderContext.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/RenderContextImpl.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/AbstractFrom.java, parent/pom.xml
=> Various small issues

integration/deltaspike-data/api/src/main/java/com/blazebit/persistence/deltaspike/data/KeysetPageRequest.java, integration/deltaspike-data/api/src/main/java/com/blazebit/persistence/deltaspike/data/KeysetPageable.java, integration/deltaspike-data/base/src/main/java/com/blazebit/persistence/deltaspike/data/base/handler/AbstractEntityViewAwareRepositoryHandler.java, integration/deltaspike-data/testsuite/src/test/java/com/blazebit/persistence/deltaspike/data/testsuite/FullEntityViewRepositoryTest.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/AbstractEntityViewAwareRepository.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/repository/KeysetPageRequest.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/repository/KeysetPageable.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentRepositoryTest.java
This adds support to set keyset extraction and count query flags via `KeysetPageable`.
Based on #832
=> Spring keyset flags

core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/CustomTypeFunctionArgumentTest.java
I wanted to test the compatibility with `TypedParameterValue`. The support had been discussed before, but we never actually tested it and I thought I would contribute my test.
=> Added CustomTypeFunctionArgumentTest

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/FlatViewTypeImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewTypeImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/visibility/VisibilityTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/visibility/model1/IdHolderView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/visibility/model2/DocumentView.java
=> [#668] Generate abstract proxy classes for super types to bridge the implementation of package private methods

core/api/src/main/java/com/blazebit/persistence/BaseCTECriteriaBuilder.java
=> Expose WindowContainerBuilder from BaseCTECriteriaBuilder

core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/JPQLNextExpressionVisitorImpl.java
=> [#852] Fix multiple partition clause issue and order by DESC parsing issue in window expressions

.travis-deploy.sh, entity-view/api/src/main/java/com/blazebit/persistence/view/spi/TransactionAccess.java, entity-view/api/src/main/java/com/blazebit/persistence/view/spi/TransactionAccessFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/tx/Hibernate4TransactionSynchronizationStrategy.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/tx/Hibernate5EntityTransactionSynchronizationStrategy.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/tx/Hibernate5JtaPlatformTransactionSynchronizationStrategy.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/tx/JtaTransactionSynchronizationStrategy.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/tx/SynchronizationRegistry.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/tx/TransactionHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/DefaultUpdateContext.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/SimpleUpdateContext.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/UpdateContext.java, integration/entity-view-spring/pom.xml, integration/entity-view-spring/src/main/java/com/blazebit/persistence/integration/view/spring/impl/SpringTransactionAccessFactory.java, integration/entity-view-spring/src/main/java/com/blazebit/persistence/integration/view/spring/impl/SpringTransactionSynchronizationStrategy.java, integration/entity-view-spring/src/main/resources/META-INF/services/com.blazebit.persistence.view.spi.TransactionAccessFactory
=> [#864] Add transaction access SPI and implement it for the entity view spring integration. Also fix snapshot uploading

build.sh, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/testsuite/pom.xml, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/ProxyFactoryJava8Test.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/model/DocumentJava8View.java
=> [#874] Test and fix for @PostCreate default method invocation

core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, documentation/src/main/asciidoc/entity-view/manual/en_US/06_filter_and_sorter_api.adoc, documentation/src/main/asciidoc/entity-view/manual/en_US/08_updatable_entity_views.adoc, documentation/src/main/asciidoc/entity-view/manual/en_US/09_basic_user_type.adoc, entity-view/api/src/main/java/com/blazebit/persistence/view/AttributeFilter.java, entity-view/api/src/main/java/com/blazebit/persistence/view/EntityViewManager.java, entity-view/api/src/main/java/com/blazebit/persistence/view/ViewFilter.java, entity-view/api/src/main/java/com/blazebit/persistence/view/spi/EntityViewMapping.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/RecordingCollection.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/RecordingMap.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewMappingImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/collections/subview/model/SubviewPersonForCollectionsSelectFetchView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/ProxyFactoryTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/AbstractEntityViewUpdateTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/converter/EntityViewUpdateBlobTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/metamodel/EntityViewMetamodelTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/rollback/EntityViewUpdateRollbackTest.java, examples/it-service-management/src/test/java/com/blazebit/persistence/examples/itsm/UpdatableCollectionTests.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/AbstractEntityViewAwareRepository.java
Fixes #861. Fixes #867. Fixes #869. Fixes #871. Fixes #873. Fixes #879
=> [#861, #867, #869, #871, #873, #879] Various small fixes

archetype/spring-boot-sample/src/main/resources/archetype-resources/pom.xml, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/DereferenceManyToOneAssociationInJoinedInheritanceHierarchyTest.java, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/IgnoreNotFoundDereferenceTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SingleValuedAssociationOneToOneJoinTableTest.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/KeysetPageableHandlerMethodArgumentResolver.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/PageRequest.java, parent/pom.xml, testsuite-base/hibernate/src/main/java/com/blazebit/persistence/testsuite/base/AbstractPersistenceTest.java, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/AbstractJpaPersistenceTest.java
Fixes #886. Fixes #887. Fixes #888
=> Fix metamodel generation for NotFound(Ignore) ManyToOne associations

core/impl/src/main/java/com/blazebit/persistence/impl/SubqueryAndExpressionBuilderListener.java, core/impl/src/main/java/com/blazebit/persistence/impl/builder/predicate/RestrictionBuilderImpl.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/Version.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/JoinOnTest.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/UnmappedBasicAttributeCascadeDeleter.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/AbstractEntityViewRemoveDocumentTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/nested/EntityViewRemoveNestedSubviewCollectionsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/nested/EntityViewRemoveNestedSubviewMapsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/nested/EntityViewRemoveNestedSubviewTest.java
=> [#892] Test and fix for RestrictionBuilder usage with multiple subquery initiator

core/api/src/main/java/com/blazebit/persistence/JoinType.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseFinalSetOperationBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/ExpressionUtils.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/OrderByManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/FullJoinTest.java
=> [#896] Support for Hibernates FULL JOIN type

core/impl/src/main/java/com/blazebit/persistence/impl/JpaUtils.java, core/impl/src/main/java/com/blazebit/persistence/impl/builder/predicate/JoinOnBuilderImpl.java, core/parser/src/main/java/com/blazebit/persistence/parser/PathTargetResolvingExpressionVisitor.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/JoinOnTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SizeTransformationTest.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/flat/ConstructorOnlyFlatViewTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/flat/FlatViewValidationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/flat/model/ConstructorOnlyPersonFlatView.java
Fixes #903. Fixes #905. Fixes #906
=> [#903, #905, #906] Fix toString issue with constructor only flat views and implemented collection fetch join validation for mapping constructors

core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/SimplePathReference.java
=> [#905] Fix support for TREAT when rendering SIZE as subquery also

core/impl/src/main/java/com/blazebit/persistence/impl/transform/SizeTransformationVisitor.java
=> [#905] Also fix TREAT issues in SIZE when the COUNT query optimization

core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/impl/src/main/java/com/blazebit/persistence/impl/WindowManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/window/AbstractWindowFunction.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/WindowFunctionTest.java
=> Inherit range clause from base window definition and adjust rendering

documentation/src/main/asciidoc/entity-view/manual/en_US/07_querying_and_pagination_api.adoc, entity-view/api/src/main/java/com/blazebit/persistence/view/EntityViewSetting.java, entity-view/api/src/main/java/com/blazebit/persistence/view/SubGraph.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewConfiguration.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilder.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/AbstractCorrelationJoinTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/AliasExpressionSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/AliasExpressionTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/AliasSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ConstrainedTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ExpressionSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ExpressionTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ParameterizedAliasExpressionSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ParameterizedAliasSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ParameterizedExpressionSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ParameterizedSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/SimpleSubqueryTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/TupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/TupleElementMapperBuilder.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedSubselectTupleListTransformer.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/EmbeddableTestEntityViewTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/EntityViewSettingTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/PrimitiveViewTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/model/EmbeddableTestEntityIdView.java
=> [#856] Implement support for entity view fetch graph

examples/spring-data-rest/src/test/java/com/blazebit/persistence/examples/spring/data/rest/repository/SampleTest.java, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/BlazePersistenceWebConfiguration.java, integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentControllerTest.java
Trying to fix the data-rest integration
=> spring-data-rest - fix the way sortResolver is determined - us springs exposed bean

integration/jackson/pom.xml, integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapper.java, integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewReferenceDeserializer.java, integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapperTest.java, integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/SomeEntity.java, integration/jackson/src/test/resources/META-INF/persistence.xml, integration/spring-data/rest/src/main/java/com/blazebit/persistence/spring/data/rest/impl/json/EntityViewAwareMappingJackson2HttpMessageConverter.java
=> [#928] Fix issues Spring MVC entity view deserialization issues and new features for jackson deserialization

core/impl/src/main/java/com/blazebit/persistence/impl/ConjunctionPathExpressionFindingVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/ImplicitJoinCorrelationPathReplacementVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/PredicateManager.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/EmbeddableSimpleTest.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/Application.java, examples/spring-data-graphql/src/main/resources/META-INF/persistence.xml, examples/spring-data-graphql/src/test/java/com/blazebit/persistence/examples/spring/data/graphql/repository/AbstractSampleTest.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLRelayConnection.java
=> [#947] Preserve cardinality in synthetic EXISTS subquery for association usage in ON

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/ConstantifiedJoinNodeAttributeCollector.java, core/impl/src/main/java/com/blazebit/persistence/impl/FunctionalDependencyAnalyzerVisitor.java, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue969Test.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/mapper/Mappers.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedBatchTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedSubselectTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/BasicCorrelator.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/SubviewCorrelator.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/EntityViewUpdaterImpl.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/subselectsubset/SubselectSubsetCorrelationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/subselectsubset/model/DocumentEmbeddingViewSubselectWithoutIdView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/subselectsubset/model/DocumentSubselectElementCollectionView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/subselectsubset/model/NameObjectView.java
=> [#854, #969] Using SELECT or SUBSELECT fetch strategies for element collections produces a null entry

integration/spring-data/webmvc/src/main/java/com/blazebit/persistence/spring/data/webmvc/KeysetPageableArgumentResolver.java, integration/spring-data/webmvc/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/BlazePersistenceWebConfiguration.java, integration/spring-data/webmvc/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/KeysetPageableHandlerMethodArgumentResolver.java
=> [#921] Fix spring-data-webmvc integration configuration

core/impl/src/main/java/com/blazebit/persistence/impl/JpaUtils.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/nullfn/NullfnFunction.java, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue992Test.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CTETest.java
=> Null rendering fixes

core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue227Test.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomBasicCollectionPersister.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomOneToManyPersister.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectCollectionLoader.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/CustomSubselectOneToManyLoader.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/SubselectLoaderUtils.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/SubselectPreparedStatementProxyHandler.java
=> [#993] Fix problems with parameters in the select clause when using Hibernate subselect fetching for associations

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue1000Test.java
=> [#1000] Reproducer count query generation inline CTE join constantification

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/constructor/ConstructorInheritanceTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/constructor/model/DocumentBaseView.java
=> [#1007] Fix using constructor in polymorphic entity view inheritance structure

CHANGELOG.md, checkstyle-rules/src/main/resources/blaze-persistence/checkstyle-config.xml, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SubqueryTest.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/ListSetAction.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/FusedCollectionIndexActions.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/IndexedListAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/MapAttributeFlusher.java, entity-view/impl/src/test/java/com/blazebit/persistence/view/impl/update/flush/FusedCollectionIndexActionsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/flatview/simple/mutable/EntityViewUpdateSimpleMutableFlatViewCollectionsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/flatview/simple/mutable/EntityViewUpdateSimpleMutableFlatViewMapsTest.java
=> [#1010] Fix missing updates of indexed collection elements when clearing and re-adding dirty elements

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/testsuite/pom.xml, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/AbstractCoreTest.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/Sub1.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/Sub2.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/EmbeddableSimpleTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TreatMultiLevelTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TreatTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TreatedEntityJoinTest.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedBatchTupleListTransformer.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/embedded/EmbeddedCorrelationTest.java, jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/TreatTest.java
=> [#1005] Fix contradictory WHERE condition for multiple TREAT expression target types per node

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/CollectionMappingLiteral.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/IdMappingLiteral.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/MappingLiteral.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/constructor/ConstructorInheritanceTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/constructor/model/ParameterNewDocumentView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/constructor/model/ParameterOldDocumentView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/constructor/model/SuperTypeParameterDocumentBaseView.java
=> [#1025] Fix NoSuchMethodException issue with entity view inheritance where superclass has parameters but subclass has none

CHANGELOG.md, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TreatTest.java, documentation/src/main/asciidoc/entity-view/manual/en_US/04_mappings.adoc, entity-view/api/src/main/java/com/blazebit/persistence/view/EntityViewManager.java, entity-view/api/src/main/java/com/blazebit/persistence/view/spi/EntityViewConfiguration.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewConfigurationImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/SerializableEntityViewManager.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/mapper/ConvertOperationBuilderImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/mapper/ViewMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CompositeAttributeFlusher.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/ProxyFactoryEmeddableTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/ProxyFactoryJava8Test.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/ProxyFactoryTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/model/UpdatableEmbeddableTestEntityView.java
=> [#931] Introduce a way to do global mapping parameter registration

CHANGELOG.md, integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapper.java, integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapperTest.java
=> [#1040] Fix collection deserialization issues with Jackson

CHANGELOG.md, core/parser/src/main/java/com/blazebit/persistence/parser/PathTargetResolvingExpressionVisitor.java, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue546Test.java, documentation/src/main/asciidoc/entity-view/manual/en_US/06_filter_and_sorter_api.adoc, entity-view/api/src/main/java/com/blazebit/persistence/view/EntityViewSetting.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/ScalarTargetResolvingExpressionVisitor.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractMethodAttribute.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImpl.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/ValidationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/filter/basic/AttributeFilterTest.java, integration/hibernate-4.2/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate4Integrator.java, integration/hibernate-4.3/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate43Integrator.java, integration/hibernate-5.2/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate52Integrator.java, integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate53Integrator.java, integration/hibernate-5/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate5Integrator.java, integration/hibernate-6.0/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate60Integrator.java, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/AbstractJpaPersistenceTest.java
Fixes #727. Fixes #689. Fixes #482. Fixes #546. Fixes #999
=> [#727] Allow enabling multiple entity view attribute filters

CHANGELOG.md, core/api/src/main/java/com/blazebit/persistence/BaseModificationCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractDeleteCollectionCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractInsertCollectionCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractUpdateCollectionCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseDeleteCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseUpdateCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinNode.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/query/CollectionDeleteModificationQuerySpecification.java, core/impl/src/main/java/com/blazebit/persistence/impl/query/CollectionUpdateModificationQuerySpecification.java, core/parser/src/main/java/com/blazebit/persistence/parser/EqualityCheckingVisitor.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/IndexedNode.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/KeyedNode.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CollectionRoleDeleteTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CollectionRoleInverseDeleteTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CollectionRoleUpdateTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/DeleteTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/UpdateTest.java, entity-view/api/src/main/java/com/blazebit/persistence/view/EntityViewSetting.java, jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/UpdateTest.java
=> [#908] Support implicit joins for DELETE and UPDATE statements

core/impl/src/main/java/com/blazebit/persistence/impl/function/exist/ExistFunction.java
=> [#1058] Fix rendering of extended exists predicate for performance

.travis-deploy.sh, .travis.yml, CHANGELOG.md, core/api/src/main/java/com/blazebit/persistence/spi/JpaProvider.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractModificationCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseUpdateCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/CachingJpaProvider.java, core/impl/src/main/java/com/blazebit/persistence/impl/FunctionalDependencyAnalyzerVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/JpaUtils.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/parser/src/main/java/com/blazebit/persistence/parser/util/JpaMetamodelUtils.java, core/parser/src/test/java/com/blazebit/persistence/parser/TestLiterals.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CTETest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/IdClassAttributePaginationTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/JoinTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/KeysetPaginationTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/OptimizedKeysetPaginationRowValueConstructorTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/OptimizedKeysetPaginationTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationEmbeddedIdTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/UpdateTest.java, documentation/src/main/asciidoc/core/manual/en_US/expressions.adoc, documentation/src/main/asciidoc/core/manual/en_US/from_clause.adoc, documentation/src/main/asciidoc/entity-view/manual/en_US/mappings.adoc, integration/datanucleus-5.1/src/main/java/com/blazebit/persistence/integration/datanucleus/DataNucleus51JpaProvider.java, integration/datanucleus/src/main/java/com/blazebit/persistence/integration/datanucleus/DataNucleusJpaProvider.java, integration/eclipselink/src/main/java/com/blazebit/persistence/integration/eclipselink/EclipseLinkJpaProvider.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java, integration/openjpa/src/main/java/com/blazebit/persistence/integration/openjpa/OpenJPAJpaProvider.java, jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/UpdateTest.java
Fixes #615. Fixes #1063. Fixes #1066.
=> [#615, #1063, #1066] Various fixes

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateExtendedQuerySupport.java
=> [#1108] Fix accidental wrong sharing of executor for DML returning queries and support using different collection types for updatable attributes

CHANGELOG.md, core/api/src/main/java/com/blazebit/persistence/spi/JpqlFunctionGroup.java, core/api/src/main/java/com/blazebit/persistence/spi/JpqlFunctionKind.java, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderConfigurationImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderFactoryImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/GroupByExpressionGatheringVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/impl/src/main/java/com/blazebit/persistence/impl/transform/SizeTransformationVisitor.java, core/parser/src/main/java/com/blazebit/persistence/parser/FunctionKind.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/AbstractExpressionFactory.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/ExpressionFactoryImpl.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/JPQLNextExpressionVisitorImpl.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/SubqueryExpressionFactory.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/WindowDefinition.java, core/parser/src/test/java/com/blazebit/persistence/parser/AbstractParserTest.java, core/parser/src/test/java/com/blazebit/persistence/parser/AbstractTestExpressionFactory.java, core/parser/src/test/java/com/blazebit/persistence/parser/GeneralParserTest.java, core/parser/src/test/java/com/blazebit/persistence/parser/SimpleCachingExpressionFactoryPerformanceTest.java, core/parser/src/test/java/com/blazebit/persistence/parser/SimpleCachingExpressionFactoryTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/WindowFunctionTest.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ExpressionCorrelationJoinTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/ParameterizedExpressionCorrelationJoinTupleElementMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/CorrelatedSubviewJoinTupleTransformerFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/VersionAttributeFlusher.java
Fixes #1117, Fixes #1118. Fixes #1120
=> [#1117, #1118] Implicit group by window function and OptimisticLock issue fix

CHANGELOG.md, entity-view/api/src/main/java/com/blazebit/persistence/view/metamodel/ViewMetamodel.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/ScalarTargetResolvingExpressionVisitor.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AttributeMapping.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewMetamodelImpl.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/ValidationTest.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/EntityViewSortUtil.java
=> [#1126] Report more appropriate errors instead of throwing NPEs when encountering invalid arguments

CHANGELOG.md, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateExtendedQuerySupport.java
=> [#1160] Fix Hibernate 5.4.19 integration issues

CHANGELOG.md, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue1167Test.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java
=> [#1167] Fix boot exception when using Hibernate @Where on entity level

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/DefaultDbmsDialect.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CountQueryTest.java, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/AbstractJpaPersistenceTest.java
=> [#448] Add support for secondary entity view roots

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/AbstractViewToEntityMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/CreateOnlyViewToEntityMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/EmbeddableUpdaterBasedViewToEntityMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/InverseViewToEntityMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/LoadOrPersistViewToEntityMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/ReferenceEntityLoader.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/UpdaterBasedViewToEntityMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/EntityViewUpdaterImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/InverseFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/TypeDescriptor.java
=> [#1176] Fix concurrency issue during EntityViewUpdaterImpl initialization which can lead to a NPE

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionAttributeFlusher.java
=> [#1179] Fix NPE during flush for views that were converted with CREATE_NEW and contain an updatable inverse mapping

CHANGELOG.md, examples/spring-hateoas/src/main/java/com/blazebit/persistence/examples/spring/hateoas/controller/CatRestController.java, examples/spring-hateoas/src/main/java/com/blazebit/persistence/examples/spring/hateoas/repository/CatViewRepository.java, examples/spring-hateoas/src/main/java/com/blazebit/persistence/examples/spring/hateoas/view/CatWithOwnerView.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/AbstractPartTreeBlazePersistenceQuery.java
=> [#1189] Fix NPE when no specification is given and keyset page is not applied for PartTreeQuery

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/GroupByExpressionGatheringVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/GroupByManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/HavingManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/MainQuery.java, core/impl/src/main/java/com/blazebit/persistence/impl/OrderByManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/ParameterManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/impl/src/main/java/com/blazebit/persistence/impl/SelectManager.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/ExpressionCopyContext.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/ExpressionCopyContextMap.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/PathExpression.java, core/parser/src/main/java/com/blazebit/persistence/parser/util/TypeConverter.java, core/parser/src/main/java/com/blazebit/persistence/parser/util/TypeConverterContributor.java, core/parser/src/main/java/com/blazebit/persistence/parser/util/TypeUtils.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/AbstractCoreTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CaseWhenTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/GroupByTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/HavingTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/JpqlFunctionTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/KeysetPaginationNullsTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/OptimizedKeysetPaginationNullsTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SelectTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SizeTransformationTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SubqueryTest.java
=> [#1185] Fix generation of implicit group by expressions that contain parameters

CHANGELOG.md, integration/jaxrs/src/main/java/com/blazebit/persistence/integration/jaxrs/EntityViewMessageBodyReader.java
=> [#1195] Allow overriding the ObjectMapper used for deserializing entity views in the JAX-RS integration

integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java, integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java
Support aliases in CTE binds
Fixes #1198
=>  [#1198] Support aliases in CTE binds

documentation/src/main/asciidoc/core/manual/en_US/querydsl.adoc
@AFbenHassine took the time to review the QueryDSL module and its documentation. This PR brings a few improvements to the documentation based on his questions and remarks.
- Fixed indentation for some headers
- Remove confusing use of recursive CTE's where any Entity would be fine
- Remove generic qualification where not required
- A little bit more explanation how the values clauses work and what the alias is for
- Some queries referred to a "cat" alias in a "Book" variable, I fixed those ;-)
=> Fix QueryDSL integration documentation

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/tomultiset/ToMultisetFunction.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/InlineCTETest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/limit/LimitTest.java
=> [#1193] Test and fix for implicit join in lateral join correlation path array expression index

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/WindowManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/transform/SubqueryRecursiveExpressionVisitor.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationTest.java
=> [#1209] PaginatedCriteriaBuilder use case broke due to fix for implicit group by generation

entity-view/impl/pom.xml, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/SubqueryProviderHelper.java, entity-view/impl/src/test/java/com/blazebit/persistence/view/impl/SubqueryProviderHelperTest.java, parent/pom.xml
=> [#826] Support alternative constructors for subquery providers

core/api/src/main/java/com/blazebit/persistence/ConfigurationProperties.java, documentation/src/main/asciidoc/core/manual/en_US/configuration.adoc, documentation/src/main/asciidoc/entity-view/manual/en_US/quarkus.adoc, integration/quarkus/runtime/src/main/java/com/blazebit/persistence/integration/quarkus/runtime/BlazePersistenceInstanceConfiguration.java
=> [#1220] Make query plan caching configurable in Quarkus

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/EntityViewUpdaterImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/AbstractPluralAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/BasicAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionElementAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CompositeAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/DirtyAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/EmbeddableAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/SubviewAttributeFlusher.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/entity/LegacyOrderPosition.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/entity/LegacyOrderPositionEmbeddable.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/entity/LegacyOrderPositionId.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/embedded/complex/EntityViewUpdateSubviewInverseEmbeddedComplexTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/embedded/entityid/EntityViewUpdateSubviewInverseEmbeddedEntityIdTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/embedded/simple/EntityViewUpdateSubviewInverseEmbeddedSimpleTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/embedded/simple/model/UpdatableLegacyOrderPositionEmbeddableView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/simple/mutable/EntityViewUpdateSimpleMutableSubviewCollectionsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/simple/mutable/EntityViewUpdateSimpleMutableSubviewMapsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/simple/mutable/EntityViewUpdateSimpleMutableSubviewTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/simple/mutable/model/UpdatableNameObjectView.java
=> [#1226] Fix issues with flushing of embeddables/flat views for entity views retrieved by EntityViewManager.getReference()

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/EntityViewUpdaterImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CompositeAttributeFlusher.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/embedded/simple/EntityViewUpdateSubviewInverseEmbeddedSimpleTest.java
=> [#1208] Fix issues with EntityViewManager.getEntityReference when used with embedded id entity types

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinNode.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SubqueryTest.java
=> [#1240] Reorder explicit join nodes into the appropriate table references according to their dependencies

CHANGELOG.md, core/api/src/main/java/com/blazebit/persistence/GroupByBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderConfigurationImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/grouping/GroupingFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/groupingsets/CubeFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/groupingsets/GroupingSetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/groupingsets/GroupingSetsFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/groupingsets/RollupFunction.java, documentation/src/main/asciidoc/core/manual/en_US/group_by_having_clause.adoc, documentation/src/main/asciidoc/core/manual/en_US/jpql_functions.adoc
=> [#1124] Add grouping sets support

documentation/src/main/asciidoc/entity-view/manual/en_US/spring_data.adoc
Fix typo in current Spring Data integration documentation
=> Fix typo and markup in Spring Data integration documentation

CHANGELOG.md, checkstyle-rules/src/main/resources/blaze-persistence/checkstyle-config.xml, core/api/src/main/java/com/blazebit/persistence/spi/JpaProvider.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/CachingJpaProvider.java, core/impl/src/main/java/com/blazebit/persistence/impl/ConstantifiedJoinNodeAttributeCollector.java, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderFactoryImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinNode.java, core/impl/src/main/java/com/blazebit/persistence/impl/MainQuery.java, core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/impl/src/main/java/com/blazebit/persistence/impl/TreatedJoinAliasInfo.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/AbstractCoreTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TreatMultiLevelTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TreatTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TreatedEntityJoinTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/treat/builder/RootTreatTest.java, examples/showcase/runner/cdi/pom.xml, integration/datanucleus-5.1/src/main/java/com/blazebit/persistence/integration/datanucleus/DataNucleus51JpaProvider.java, integration/datanucleus/src/main/java/com/blazebit/persistence/integration/datanucleus/DataNucleusJpaProvider.java, integration/deltaspike-data/testsuite/pom.xml, integration/eclipselink/src/main/java/com/blazebit/persistence/integration/eclipselink/EclipseLinkJpaProvider.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java, integration/openjpa/src/main/java/com/blazebit/persistence/integration/openjpa/OpenJPAJpaProvider.java, jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/TreatTest.java
=> [#1174] Replace faulty treat rendering optimizations

integration/entity-view-spring/src/main/java/com/blazebit/persistence/integration/view/spring/impl/EntityViewConfigurationDelegate.java, integration/entity-view-spring/src/test/java/com/blazebit/persistence/integration/view/spring/AnnotationClassLoaderTest.java
Use ClassUtils.forName instead Class.forName to correctly use the ClassLoader associated with Spring
Fixes #1247
Should fix a NPE on application startup with spring-boot-devtools
=> #1247 fix devtools npe

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/MapAttributeFlusher.java
=> [#1243] Fix remove by owner id of map attributes to use mapping instead of attribute name

CHANGELOG.md, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java
=> [#1260] Ignore GarphQL __typename Meta field in entity view integration

CHANGELOG.md, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/TypeUtils.java
=> [#1262] Fix entity view annotation processor generation of casts for attributes containing annotations

.github/ci-prerequisites.sh, .github/workflows/ci.yaml, CHANGELOG.md, build.sh, core/parser/src/main/java/com/blazebit/persistence/parser/expression/ExpressionCache.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ChainingObjectBuilder.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformator/TupleTransformator.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformator/TupleTransformatorFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/CollectionMultisetTupleListTransformerFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/SingularMultisetTupleListTransformerFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/FusedCollectionElementActions.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/simple/EntityViewUpdateSubviewInverseSimpleTest.java, parent/pom.xml
=> [#1258] Coalesce inverse collection operations 

.github/workflows/ci.yaml, CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/BaseFinalSetOperationBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/PostgreSQLDbmsDialect.java, core/impl/src/main/java/com/blazebit/persistence/impl/query/AbstractCustomQuery.java, core/impl/src/main/java/com/blazebit/persistence/impl/query/CustomQuerySpecification.java, core/impl/src/main/java/com/blazebit/persistence/impl/query/SetOperationQuerySpecification.java, core/impl/src/main/java/com/blazebit/persistence/impl/query/TypedQueryWrapper.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/SetOperationTest.java, examples/quarkus/testsuite/native/db2/pom.xml, examples/quarkus/testsuite/native/db2/src/main/java/com/blazebit/persistence/examples/quarkus/testsuite/nativedb2/Dummy.java, examples/quarkus/testsuite/native/db2/src/main/resources/application.properties, examples/quarkus/testsuite/native/db2/src/test/java/com/blazebit/persistence/examples/quarkus/testsuite/db2/QuarkusExampleIT.java, examples/quarkus/testsuite/native/pom.xml
=> [#1274, #1276] Fix set operation query wrapping and unwrapping issues

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AnnotationMappingReader.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/MethodAttributeMapping.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/ViewMetamodelTest.java
=> [#1200] Prefer abstract class method over interface method in metamodel if attribute mappings are equal

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImpl.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/CreatableAbstractEntityTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/model/SingleTableBaseAbstractEntityMappingValidationView.java, integration/datanucleus/src/main/java/com/blazebit/persistence/integration/datanucleus/DataNucleusJpaProvider.java
=> [#840] Validate that entity type for creatable entity view is non-abstract

CHANGELOG.md, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java
=> [#1255] Fix GraphQL integration issue when encountering enum types multiple times

core/impl/src/main/java/com/blazebit/persistence/impl/dialect/OracleDbmsLimitHandler.java
=> [#1283] Don't try to assume Oracle limit/offset parameters are given as literals

CHANGELOG.md, entity-view/api/src/main/java/com/blazebit/persistence/view/spi/type/EntityViewProxy.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/mapper/ViewMapper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ConvertReflectionInstantiator.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/ImplementationClassWriter.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/AViewImpl.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/BViewImpl.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/convert/view/ConvertViewTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/proxy/ProxyFactoryTest.java
=> [#1175] Retain entity view kind when converting entity view if possible

CHANGELOG.md, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/AbstractHibernateEntityManagerFactoryIntegrator.java
=> [#1281] Improve dialect detection for MariaDB dialects

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderConfigurationImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/CockroachSQLDbmsDialect.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/AbstractHibernateEntityManagerFactoryIntegrator.java, integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapper.java, integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapperTest.java, integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/SomeEntity.java, integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/StringListConverter.java
=> [#1295, #1289] Jackson singular collection deserialization fixes and Cockroach dialect

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/AbstractExpressionFactory.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/DocumentHolder.java, core/testsuite/src/main/resources/META-INF/persistence.xml, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/MetamodelBuildingContextImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/EntityViewUpdaterImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/InverseFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/ViewCollectionRemoveListener.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/AttributeMatchesEntityNameTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/embedded/complex/EntityViewUpdateSubviewInverseEmbeddedComplexTest.java
=> [#1294, #1299] Various fixes

documentation/src/main/asciidoc/core/manual/en_US/getting_started.adoc, documentation/src/main/asciidoc/core/manual/en_US/querydsl.adoc, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/AbstractBlazeJPAQuery.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/HintsAccessor.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextTemplates.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/WindowFunction.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/WindowOver.java, pom.xml, website/src/main/jbake/content/downloads.adoc, website/src/main/jbake/content/news/2020/blaze-persistence-1.5.0-Alpha2-release.adoc
=> QueryDSL 5 Support

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/parser/src/main/java/com/blazebit/persistence/parser/util/TypeUtils.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/AbstractCoreTest.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TemporalLiteralRenderingTest.java, jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/SelectTest.java
=> [#1321] Fix support for Java 8 type temporal literals

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/accessor/Accessors.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/AbstractEntityLoader.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/entity/EntityLoaders.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/EntityViewUpdaterImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/TypeDescriptor.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/natural/EntityViewUpdateSimpleImmutableSubviewWithPkIdTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/natural/model/BookIsbnWithPkView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/natural/model/BookPkWithIsbnView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/natural/model/UpdatableBookReferencePkView.java
=> [#1334] Fix issues with persisting updatable non-PK subview mapping referring to PK-Id view

.github/workflows/ci.yaml, CHANGELOG.md, README.md, examples/showcase/runner/spring/pom.xml, examples/spring-data-graphql/pom.xml, examples/spring-data-webflux/pom.xml, examples/spring-data-webmvc/pom.xml, examples/spring-hateoas/pom.xml, integration/entity-view-spring/pom.xml, integration/spring-data/base/pom.xml, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/repository/KeysetPageRequest.java, integration/spring-data/testsuite/webflux/pom.xml, integration/spring-data/testsuite/webmvc/pom.xml, integration/spring-data/webflux/pom.xml, integration/spring-data/webmvc/pom.xml, integration/spring-hateoas/webmvc/pom.xml, parent/pom.xml
=> [#1333] Add support for Spring Boot/Data 2.5

CHANGELOG.md, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/TypeUtils.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/TypeUseAnnotation.java
=> [#1324] Fix issues with entity-view annotation processor and type use annotations

CHANGELOG.md, core/parser/src/main/java/com/blazebit/persistence/parser/PathTargetResolvingExpressionVisitor.java, entity-view/api/src/main/java/com/blazebit/persistence/view/EntityViewSetting.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewConfiguration.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/ScalarTargetResolvingExpressionVisitor.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/UpdatableExpressionVisitor.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilder.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/NullTupleTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/SubviewTupleTransformerFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/CorrelatedSubviewJoinTupleTransformerFactory.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/EntityViewSettingTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/model/DocumentWithEntityView.java, integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/AbstractHibernateEntityManagerFactoryIntegrator.java
=> [#1331] Automatically fetch attributes necessary for attribute sorters/filters

CHANGELOG.md, examples/pom.xml, examples/spring-data-dgs/README.md, examples/spring-data-dgs/pom.xml, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/Application.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/GraphQLProvider.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/config/BlazePersistenceConfiguration.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/fetcher/CatFetcher.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/model/Cat.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/model/Person.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/repository/CatJpaRepository.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/repository/CatViewRepository.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/view/CatCreateView.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/view/CatSimpleView.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/view/CatUpdateView.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/view/CatWithOwnerView.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/view/PersonIdView.java, examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/view/PersonSimpleView.java, examples/spring-data-dgs/src/main/resources/application.properties, examples/spring-data-dgs/src/main/resources/schema/schema.graphqls, examples/spring-data-dgs/src/test/java/com/blazebit/persistence/examples/spring/data/dgs/repository/AbstractSampleTest.java, examples/spring-data-dgs/src/test/java/com/blazebit/persistence/examples/spring/data/dgs/repository/SampleTest.java, examples/spring-data-dgs/src/test/resources/META-INF/test-config.xml, examples/spring-data-dgs/src/test/resources/logback-test.xml, integration/graphql/pom.xml, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java
=> [#1335] Ensure graphql-java 9.2 - 16.2 work properly and add a Netflix DGS sample application

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/ExpressionUtils.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java, integration/graphql/pom.xml, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/InternalQuery.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/RenderContext.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/RenderContextImpl.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/AbstractFrom.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/AbstractPath.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/CollectionAttributeJoin.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/EntityJoin.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/ListAttributeJoin.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/MapAttributeJoin.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/MapKeyBasePath.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/RootImpl.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/SetAttributeJoin.java, jpa-criteria/impl/src/main/java/com/blazebit/persistence/criteria/impl/path/SingularAttributeJoin.java, jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/EmbeddableJoinTest.java
Fixes #1352. Fixes #1349. Fixes #1350
=> [#1352, #1349, #1350] Infer nullability from entity view mappings for attributes in GraphQL schema

CHANGELOG.md, core/api/src/main/java/com/blazebit/persistence/FullQueryBuilder.java, core/impl/pom.xml, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/CTEManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/OrderByManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/SubqueryInitiatorFactory.java, core/parser/src/main/antlr4/com/blazebit/persistence/parser/JPQLNextParser.g4, core/parser/src/main/java/com/blazebit/persistence/parser/expression/JPQLNextExpressionVisitorImpl.java, core/testsuite/pom.xml, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationTest.java, documentation/src/main/asciidoc/entity-view/manual/en_US/fetch_strategies.adoc, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/CollectionMultisetTupleListTransformerFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/SingularMultisetTupleListTransformerFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedSubselectTupleListTransformer.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionAttributeFlusher.java, entity-view/testsuite/pom.xml, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/expression/ExpressionCorrelationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/subselectsubset/SubselectSubsetCorrelationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/cte/model/DocumentWithCTE.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/subview/inverse/embedded/simple/EntityViewUpdateSubviewInverseEmbeddedSimpleTest.java, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/cleaner/AbstractMySQLDatabaseCleaner.java
Fixes #1354. Fixes #1355. Fixes #1358. Fixes #1357. Fixes #370
=> Various fixes

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedTypedQueryImpl.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationTest.java
=> [#1370] Return proper totalSize on PagedList also if the requested page is empty

CHANGELOG.md, integration/quarkus/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java, integration/quarkus/runtime/pom.xml, integration/quarkus/runtime/src/main/resources/META-INF/quarkus-extension.properties, roadmap.asciidoc
=> [#1371] Get rid of a startup warning with Quarkus 2.4.0+

CHANGELOG.md, documentation/src/main/asciidoc/entity-view/manual/en_US/quarkus.adoc, examples/it-service-management/src/test/java/com/blazebit/persistence/examples/itsm/EnversTests.java, examples/quarkus/base/src/main/java/com/blazebit/persistence/examples/quarkus/base/config/BlazePersistenceConfigurator.java, examples/quarkus/testsuite/base/src/main/java/com/blazebit/persistence/examples/quarkus/testsuite/base/AbstractQuarkusExampleTest.java, integration/quarkus/runtime/src/main/java/com/blazebit/persistence/integration/quarkus/runtime/BlazePersistenceInstanceConfiguration.java, integration/quarkus/runtime/src/main/java/com/blazebit/persistence/integration/quarkus/runtime/EntityViewRecorder.java, integration/spring-data/2.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/EntityViewAwareRepositoryImpl.java, integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/AbstractEntityViewAwareRepository.java, integration/spring-data/webflux/src/main/java/com/blazebit/persistence/spring/data/webflux/impl/BlazePersistenceWebConfiguration.java, integration/spring-data/webmvc/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/BlazePersistenceWebConfiguration.java, integration/spring-hateoas/webmvc/src/main/java/com/blazebit/persistence/spring/hateoas/webmvc/HateoasAwareBlazePersistenceWebConfiguration.java
=> [#1390] Fire EntityViewConfiguration as event in Quarkus extension boot like in the CDI integration to allow customization

.github/quarkus-ecosystem-test, examples/quarkus/base/pom.xml, integration/hibernate-5.6/src/main/java/com/blazebit/persistence/integration/hibernate/CustomMultiTableBulkIdStrategy.java, integration/quarkus/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java, parent/pom.xml
=> Update to Hibernate 5.6.4.Final to fix Quarkus testsuite

.github/workflows/ci.yaml, examples/showcase/runner/spring/pom.xml, examples/spring-data-dgs/pom.xml, examples/spring-data-graphql/pom.xml, examples/spring-data-spqr/pom.xml, examples/spring-data-webflux/pom.xml, examples/spring-data-webmvc/pom.xml, examples/spring-hateoas/pom.xml, integration/entity-view-spring/pom.xml, integration/spring-data/base/pom.xml, integration/spring-data/testsuite/webflux/pom.xml, integration/spring-data/testsuite/webmvc/pom.xml, integration/spring-data/webflux/pom.xml, integration/spring-data/webmvc/pom.xml, integration/spring-hateoas/webmvc/pom.xml, integration/spring-hateoas/webmvc/src/main/java/com/blazebit/persistence/spring/hateoas/webmvc/KeysetAwarePagedResourcesAssembler.java, parent/pom.xml
=> [#1434] Support Spring Boot/Data 2.6

core/parser/src/main/antlr4/com/blazebit/persistence/parser/JPQLNextParser.g4, core/parser/src/main/java/com/blazebit/persistence/parser/expression/JPQLNextExpressionVisitorImpl.java, core/parser/src/test/java/com/blazebit/persistence/parser/ArithmeticTest.java
=> [#1474] Fix arithmetic expression parsing precedence

core/impl/src/main/java/com/blazebit/persistence/impl/function/entity/ValuesEntity.java
=> Use the column name 'val' for ValuesEntity#value to avoid keyword use in H2 2.0+

examples/quarkus/testsuite/base/src/test/resources/application.properties, examples/quarkus/testsuite/native/h2/src/test/java/com/blazebit/persistence/examples/quarkus/testsuite/h2/H2DatabaseTestResource.java
=> Use different JDBC URL for H2 native image test

examples/quarkus/testsuite/base/pom.xml, examples/quarkus/testsuite/native/h2/pom.xml
=> Change scope of quarkus-test-h2 artifact to test

CHANGELOG.md, checkstyle-rules/src/main/resources/blaze-persistence/checkstyle-config.xml, core/api/src/main/java/com/blazebit/persistence/StartOngoingSetOperationCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/MySQLDbmsDialect.java, integration/querydsl/expressions/pom.xml, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/AbstractBlazeJPAQuery.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeJPAQuery.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeJPAQueryFactory.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextSerializer.java, integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java
Closes #1443
Closes #1460
Closes #1461
Closes #1464
Closes #1516
Closes #1524
Closes #1525
=> Various querydsl fixes

entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/EntityViewAnnotationProcessor.java
=> [#1551] Make sure that annotation processor runs in compiler thread when threads=1 configured

CHANGELOG.md, documentation/src/main/asciidoc/entity-view/manual/en_US/graphql.adoc, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLNonNull.java
=> [#1549] Support marking GraphQL fields and field types as non-null in Entity Views

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/BaseFinalSetOperationBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/entity/EntityFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/query/SetTypedQuery.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CTETest.java, integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateExtendedQuerySupport.java
=> [#1563] Fix CTE inlining in set operands

CHANGELOG.md, entity-view/api/src/main/java/com/blazebit/persistence/view/metamodel/ManagedViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AnnotationMappingReader.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedFlatViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ConvertedViewType.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/JoinCorrelationBuilder.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/custom/CustomClassViewTwoStackSlotTest.java
=> [#1575] Fix custom entity view class bytecode analysis when using 2 stack slot types

CHANGELOG.md, core/api/src/main/java/com/blazebit/persistence/FromBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewSettingHelper.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/flat/FlatViewCollectionRootTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/flat/model/NameObjectView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/subquery/MappingSubqueryTest.java
=> [#1593] Applying EntityViewSetting to custom path should have inner join semantics

CHANGELOG.md, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/AttributeFilter.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/Context.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/ImportContextImpl.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/OptionalParameterUtils.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/annotation/AnnotationMetaAttribute.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/annotation/AnnotationMetaConstructor.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/annotation/AnnotationMetaEntityView.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/annotation/MetaAttributeGenerationVisitor.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/AView.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/AViewBuilder.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/AViewImpl.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/AViewMultiRelation.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/AViewRelation.java, entity-view/processor/src/test/java/com/blazebit/persistence/view/processor/model/AView_.java
=> [#1497] Treat entity view mapping parameters always as singular in annotation processor

CHANGELOG.md, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/PrimitiveFamily.java, core/testsuite/src/main/resources/META-INF/persistence.xml, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CompositeAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/UnmappedAttributeCascadeDeleterUtil.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/UnmappedBasicAttributeCascadeDeleter.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/UnmappedCollectionAttributeCascadeDeleter.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/UnmappedMapAttributeCascadeDeleter.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/simple/EntityViewRemoveCascadeOneToManyTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/simple/model/FamilyIdView.java
=> [#1520] Fix NPE on cascade delete of unmapped null one-to-one association

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/DefaultUpdateContext.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/simple/EntityViewRemoveCascadeOneToManyTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/remove/cascade/simple/model/PersonNameView.java
=> [#1606] Throw OptimisticLockException if view can't be found for entity view lifecycle listener

documentation/src/main/asciidoc/entity-view/manual/en_US/getting_started.adoc
Getting started guide referenced the wrong maven artifacts for Jakarta JPA
=> Fix maven artifact references for Jakarta JPA

core/impl/src/main/java/com/blazebit/persistence/impl/dialect/DB2DbmsDialect.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/DefaultDbmsDialect.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/H2DbmsDialect.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/MySQL8DbmsDialect.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/OracleDbmsDialect.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/PostgreSQLDbmsDialect.java, core/impl/src/main/java/com/blazebit/persistence/impl/util/SqlUtils.java, integration/jaxrs-jackson/src/test/java/com/blazebit/persistence/integration/jaxrs/jackson/testsuite/config/EntityManagerHolder.java, integration/spring-data/testsuite/webmvc/src/main/java/com/blazebit/persistence/spring/data/testsuite/webmvc/entity/Document.java, integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/DocumentProjectionEntityViewRepositoryTest.java, integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/ReadOnlyDocumentRepositoryTest.java, integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/projection/DocumentIdProjection.java, integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/projection/DocumentProjection.java, integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/repository/DocumentProjectionEntityViewRepository.java, integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/repository/ReadOnlyDocumentRepository.java, testsuite-base/hibernate/src/main/java/com/blazebit/persistence/testsuite/base/AbstractPersistenceTest.java
=> [#1104] Add test cases for various spring-data features

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/collection/RecordingMap.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/AbstractPluralAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CollectionAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/CompositeAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/EmbeddableAttributeFlusher.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/update/flush/MapAttributeFlusher.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/ClassWriter.java, entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/ImplementationClassWriter.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/flatview/simple/mutable/EntityViewUpdateSimpleMutableFlatViewTest.java, integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapperTest.java, integration/jsonb/src/test/java/com/blazebit/persistence/integration/jsonb/EntityViewJsonbDeserializerTest.java
=> [#1591] Always treat flat views for embeddable types as updates to support partial flushing

CHANGELOG.md, integration/hibernate-6.0/pom.xml
=> [#1633] Fix deployment problems with Hibernate 6 integration on Wildfly 27

CHANGELOG.md, core/parser/src/main/antlr4/com/blazebit/persistence/parser/JPQLNextParser.g4, core/parser/src/main/java/com/blazebit/persistence/parser/expression/JPQLNextExpressionVisitorImpl.java, core/parser/src/test/java/com/blazebit/persistence/parser/AbstractParserTest.java, core/parser/src/test/java/com/blazebit/persistence/parser/TestLiterals.java
=> [#1576] Fix issue with negative numeric literals in inLiterals and notInLiterals APIs

.github/quarkus-ecosystem-test
=> Fix Quarkus ANTLR shading issue

CHANGELOG.md, documentation/src/main/asciidoc/entity-view/manual/en_US/graphql.adoc, documentation/src/main/asciidoc/entity-view/manual/en_US/mappings.adoc, examples/spring-data-graphql/pom.xml, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/GraphQLProvider.java, integration/graphql-jakarta/pom.xml, integration/graphql/pom.xml, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportTest.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/TestSchemaHelpers.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/entities/Document.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/entities/Person.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/views/DocumentView.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/views/PersonView.java
Make sure that EntityViewSetting.fetches are set up correctly,
i.e. they do not include intermediate/non-leaf fields as those
cause the whole subtree to be fetched from the DB.
=> [#1653] Fix GraphQL overfetching issue

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/macro/CorrelatedSubqueryEmbeddingViewJpqlMacro.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/batchsubselect/BatchSubselectSubsetCorrelationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/batchsubselect/model/IdHolderView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/batchsubselect/model/LegacyOrderPositionDefaultIdView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/batchsubselect/model/LegacyOrderPositionElementView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/batchsubselect/model/LegacyOrderPositionView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/batchsubselect/model/LegacyOrderView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/entity/LegacyOrderPositionElement.java
=> [#1689] Fix issue with EMBEDDING_VIEW macro when used in subquery within batch loaded mapping

CHANGELOG.md, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/ValidationTest.java, integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/HibernateSqmFunctionDescriptorAdapter.java
=> [#1700] Fix issue with resolving function return types in Hibernate 6 integration

documentation/src/main/asciidoc/entity-view/manual/en_US/getting_started.adoc
Changed `blaze-persistence-entity-view-processor` to `blaze-persistence-entity-view-processor-jakarta`
=> Fixed wrong dependency in documentation

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue1713Test.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java
=> [#1713]Fix entity binding for column equivalent attributes

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AliasManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/ImplicitJoinCorrelationPathReplacementVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/JpaUtils.java, core/impl/src/main/java/com/blazebit/persistence/impl/SelectManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/transform/SizeTransformationVisitor.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/ExpressionCopyContext.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/ExpressionCopyContextForQuery.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/MapValueExpression.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/PathExpression.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/subselectsubset/SubselectSubsetCorrelationTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/correlation/subselectsubset/model/DocumentSubselectElementCollectionView.java
=> [#1708] Fix problem with query copying of paths that refer to select aliases

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderConfigurationImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/dialect/MariaDBDbmsDialect.java, integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/AbstractHibernateEntityManagerFactoryIntegrator.java
=> [#1736] Add MariaDBDbmsDialect for MariaDB support

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCTECriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/AbstractUpdateCollectionCriteriaBuilder.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseDeleteCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseFinalSetOperationBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseFinalSetOperationCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseInsertCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseSubqueryBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/BaseUpdateCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, core/impl/src/main/java/com/blazebit/persistence/impl/JoinVisitor.java, core/impl/src/main/java/com/blazebit/persistence/impl/LeafOngoingSetOperationCTECriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/LeafOngoingSetOperationCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/LeafOngoingSetOperationSubqueryBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/OngoingSetOperationCTECriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/OngoingSetOperationCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/OngoingSetOperationSubqueryBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/ResolvingQueryGenerator.java, core/impl/src/main/java/com/blazebit/persistence/impl/StartOngoingSetOperationCTECriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/StartOngoingSetOperationCriteriaBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/StartOngoingSetOperationSubqueryBuilderImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/transform/SubqueryRecursiveExpressionVisitor.java, core/parser/src/main/java/com/blazebit/persistence/parser/SimpleQueryGenerator.java, core/parser/src/main/java/com/blazebit/persistence/parser/expression/AbstractExpression.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationTest.java
=> [#1697, #1698] Fix subquery preparing re-entrance issue causing wrong query generation

entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/ClassWriter.java
=> [#1572] silence also "unchecked" warnings in EntityViewAnnotationProcessor

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/JpaUtils.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/SimpleEmbeddedIdEntity.java, core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/SimpleEmbeddedIdEntityId.java, core/testsuite/src/main/resources/META-INF/persistence.xml, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/GroupByEmbeddableTest.java
=> [#1775] Fix dropping of embeddable group by expression when nested property has same name as parent property

CHANGELOG.md, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilder.java, entity-view/impl/src/test/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTest.java
=> [#1832] Fix over-fetching of entity view data with dynamic fetches

integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java
=> [#1835] Support more advanced types for GraphQL

CHANGELOG.md, integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/HibernateJpqlFunctionAdapter.java, parent/pom.xml
=> [#1839] Fix Hibernate ORM 6.4.0.Final compatibility

integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapper.java
=> [#1878] Avoid overriding a user provided deserializer

core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderConfigurationImpl.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java
=> [#1759] Don't publish partially initialized updaters of local cache

core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderConfigurationImpl.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/cast/CastFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonget/AbstractJsonGetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonget/DB2JsonGetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonget/MSSQLJsonGetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonget/MySQLJsonGetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonget/OracleJsonGetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonget/PostgreSQLJsonGetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonset/AbstractJsonFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonset/AbstractJsonSetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonset/MSSQLJsonSetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonset/MySQL8JsonSetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/jsonset/OracleJsonSetFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/util/JpqlFunctionUtil.java, core/testsuite/src/test/java/com/blazebit/persistence/testsuite/JsonGetAndSetTest.java, documentation/src/main/asciidoc/core/manual/en_US/jpql_functions.adoc
=> [#1928] Add parameter support for JSON_GET

.github/workflows/ci.yaml, .github/workflows/latest.yaml, core/testsuite-hibernate6/pom.xml, core/testsuite-jakarta-runner/pom.xml, core/testsuite/pom.xml, entity-view/testsuite-jakarta-runner/pom.xml, entity-view/testsuite/pom.xml, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/collections/singleton/SingletonCollectionsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/embedded/entity/EmbeddedMappingEntityTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/entity/updatableonly/EntityViewUpdateUpdatableOnlyEntityCollectionsTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/update/entity/updatableonly/EntityViewUpdateUpdatableOnlyEntityMapsTest.java, integration/deltaspike-data/testsuite/pom.xml, integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateExtendedQuerySupport.java, integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/HibernateJpqlFunctionAdapter.java, integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/HibernateSqmFunctionDescriptorAdapter.java, integration/quarkus-3/deployment/pom.xml, integration/querydsl/testsuite/pom.xml, integration/spring-data/testsuite/webflux/pom.xml, integration/spring-data/testsuite/webmvc/pom.xml, jpa-criteria/testsuite-jakarta-runner/pom.xml, jpa-criteria/testsuite/pom.xml, parent/pom.xml, testsuite-base/hibernate/src/main/java/com/blazebit/persistence/testsuite/base/AbstractPersistenceTest.java, testsuite-base/hibernate6/src/main/java/com/blazebit/persistence/testsuite/base/AbstractPersistenceTest.java, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/AbstractJpaPersistenceTest.java, testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/category/NoHibernate66.java
=> [#1927] Fix support for Hibernate ORM 6.6

documentation/src/main/asciidoc/core/manual/en_US/cte.adoc, documentation/src/main/asciidoc/core/manual/en_US/querydsl.adoc
Some issues were found in the documentation and fixed.
=> Fix some errors in the documentation

CHANGELOG.md, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/Application.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/GraphQLProvider.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/model/Cat.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/model/Dog.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/model/Human.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/model/Pet.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/view/CatPetView.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/view/DogPetView.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/view/HumanWithPetsView.java, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/view/PetView.java, examples/spring-data-graphql/src/main/resources/schema.graphqls, examples/spring-data-graphql/src/test/java/com/blazebit/persistence/examples/spring/data/graphql/repository/AbstractSampleTest.java, examples/spring-data-graphql/src/test/java/com/blazebit/persistence/examples/spring/data/graphql/repository/SampleTest.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportTest.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/TestSchemaHelpers.java
=> [#1977] Support interface inheritance in GraphQL integration

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewConfiguration.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/TupleElementMapperBuilder.java, entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/transformer/correlation/AbstractCorrelatedSubselectTupleTransformer.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/InheritanceFetchesTest.java
=> [#1978] Fix SELECT/SUBSELECT fetching issues with dynamic fetching and treat mappings

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/function/stringjsonagg/PostgreSQLStringJsonAggFunction.java, core/impl/src/main/java/com/blazebit/persistence/impl/function/tostringjson/PostgreSQLToStringJsonFunction.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/fetch/multisetbig/BigMultisetTest.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/fetch/multisetbig/model/DocumentMultisetFetchView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/fetch/multisetbig/model/DocumentTemporalsView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/fetch/multisetbig/model/PersonMultisetFetchView.java, entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/fetch/multisetbig/model/SimplePersonMultisetFetchView.java
=> [#1979] Use jsonb object concat to avoid PostgreSQL 100 function argument limit

CHANGELOG.md, documentation/src/main/asciidoc/entity-view/manual/en_US/graphql.adoc, examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/view/DogPetView.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/DefaultFetchMapping.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLDefaultFetch.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportTest.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/TestSchemaHelpers.java
=> [#1972] Support conditional fetches for entity views based on GraphQL selection set

.gitignore, CHANGELOG.md, integration/graphql-dgs-7.0/pom.xml, integration/graphql-dgs-7.0/src/main/java/com/blazebit/persistence/integration/graphql/dgs/mapper/EntityViewInputObjectMapper.java, integration/graphql-dgs-7.0/src/test/java/com/blazebit/persistence/integration/graphql/dgs/SampleTest.java, integration/graphql-dgs-7.0/src/test/java/com/blazebit/persistence/integration/graphql/dgs/fetcher/CatGraphQLApi.java, integration/graphql-dgs-7.0/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinCreateView.kt, integration/graphql-dgs-7.0/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinSimpleCreateView.kt, integration/graphql-dgs-7.0/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinSimpleView.kt, integration/graphql-dgs-7.0/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinUpdateView.kt, integration/graphql-dgs-7.0/src/test/resources/schema/schema.graphqls, integration/graphql-dgs/pom.xml, integration/graphql-dgs/src/main/java/com/blazebit/persistence/integration/graphql/dgs/mapper/EntityViewInputObjectMapper.java, integration/graphql-dgs/src/test/java/com/blazebit/persistence/integration/graphql/dgs/SampleTest.java, integration/graphql-dgs/src/test/java/com/blazebit/persistence/integration/graphql/dgs/fetcher/CatGraphQLApi.java, integration/graphql-dgs/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinCreateView.kt, integration/graphql-dgs/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinSimpleCreateView.kt, integration/graphql-dgs/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinSimpleView.kt, integration/graphql-dgs/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinUpdateView.kt, integration/graphql-dgs/src/test/resources/schema/schema.graphqls
=> [#1712] Support Kotlin entity views in GraphQL DGS integration

CHANGELOG.md, core/impl/src/main/java/com/blazebit/persistence/impl/util/SqlUtils.java, integration/graphql-dgs-7.0/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinCreateView.kt, integration/graphql-dgs-7.0/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinSimpleView.kt, integration/graphql-dgs-7.0/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinUpdateView.kt, integration/graphql-dgs/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinCreateView.kt, integration/graphql-dgs/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinSimpleView.kt, integration/graphql-dgs/src/test/kotlin/com/blazebit/persistence/integration/graphql/dgs/view/CatKotlinUpdateView.kt, integration/graphql/pom.xml, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/KotlinSupport.java
=> [#2019] Improve GraphQL nullability determination for collections and Kotlin types

CHANGELOG.md, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLDefaultFetch.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLDefaultFetches.java, integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java, integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/GraphQLDeserializerTest.java, integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java
Fixes #2038. Fixes #2039. Fixes #2045
=> [#2039] Allow adding custom GraphQL deserialization types and auto-add java.time.Ser for time types

.github/workflows/ci.yaml, CHANGELOG.md, dist/bom/pom.xml, dist/full/pom.xml, integration/spring-data/3.4/pom.xml, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/query/CriteriaQueryParameterBinder.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/query/EntityViewAwareRepositoryInformation.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/query/EntityViewAwareRepositoryMetadataImpl.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/query/ParameterMetadataProviderImpl.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/BlazePersistenceRepositoryFactory.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/BlazePersistenceRepositoryFactoryBean.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/DefaultRepositoryInformation.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/EntityViewAwareRepositoryImpl.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/MethodLookups.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/QueryCollectingQueryCreationListener.java, integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/repository/QueryExecutionResultHandler.java, integration/spring-data/pom.xml, integration/spring-data/testsuite/webflux-jakarta-runner/pom.xml, integration/spring-data/testsuite/webflux/pom.xml, integration/spring-data/testsuite/webmvc-jakarta-runner/pom.xml, integration/spring-data/testsuite/webmvc/pom.xml, integration/spring-data/webflux/pom.xml, integration/spring-data/webmvc/pom.xml, integration/spring-hateoas/webmvc-jakarta/pom.xml, integration/spring-hateoas/webmvc/pom.xml, parent/pom.xml
=> [#1958] Add Spring Boot/Data 3.4 and 3.5 support

integration/entity-view-spring-6.0/src/main/java/com/blazebit/persistence/integration/view/spring/impl/SpringTransactionSynchronizationStrategy.java, integration/entity-view-spring/src/main/java/com/blazebit/persistence/integration/view/spring/impl/SpringTransactionSynchronizationStrategy.java
=> [#1985] Suspend and resume transaction identifier object for Spring

parent/pom.xml
=> Update Spring versions
