core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java
core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java
core/impl/src/main/java/com/blazebit/persistence/impl/util/SqlUtils.java
core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/DocumentTupleEntity.java
core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/EmbeddedDocumentTupleEntity.java
core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/EmbeddedDocumentTupleEntityId.java
core/testsuite/src/main/resources/META-INF/persistence.xml
core/testsuite/src/test/java/com/blazebit/persistence/testsuite/Issue358Test.java

Before we simply created an example query containing the plain attributes in the select, but that has the effect that joins are generated for *ToOne relations. I fixed that by using the ids of the *ToOne types instead in the select clause. I also simplified the select column extraction of the example query.

Fix for #358

---

core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/PrimitiveDocument.java
entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractMethodAttribute.java
entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractMethodPluralAttribute.java
entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/PrimitiveViewTest.java
entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/model/PrimitiveSimpleDocumentView.java

A simple fix that unifies attribute name determination so that primitive boolean getters work too.

#375 Test and fix

---

CHANGELOG.md
core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java
core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java
core/impl/src/main/java/com/blazebit/persistence/impl/BaseSubqueryBuilderImpl.java
core/impl/src/main/java/com/blazebit/persistence/impl/FinalSetOperationCTECriteriaBuilderImpl.java
core/impl/src/main/java/com/blazebit/persistence/impl/FinalSetOperationCriteriaBuilderImpl.java
core/impl/src/main/java/com/blazebit/persistence/impl/FinalSetOperationSubqueryBuilderImpl.java
core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java
core/impl/src/main/java/com/blazebit/persistence/impl/JoinTreeNode.java
core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java
core/impl/src/main/java/com/blazebit/persistence/impl/SelectManager.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/AbstractExpressionFactory.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/DateLiteral.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/EntityLiteral.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/EnumLiteral.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/NumericLiteral.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/StringLiteral.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/TimeLiteral.java
core/parser/src/main/java/com/blazebit/persistence/impl/expression/TimestampLiteral.java
core/parser/src/main/java/com/blazebit/persistence/impl/util/TypeUtils.java
core/testsuite/src/test/java/com/blazebit/persistence/testsuite/DateExtractTest.java
core/testsuite/src/test/java/com/blazebit/persistence/testsuite/JoinTest.java
documentation/src/main/asciidoc/core/manual/en_US/04_from_clause.adoc
jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/JoinTest.java
testsuite-base/datanucleus/src/main/java/com/blazebit/persistence/testsuite/base/SanePostgreSQLAdapter.java
testsuite-base/datanucleus/src/main/resources/plugin.xml

This is required for being able to implement #257 so hurry with reviewing ;)

#190 - Test and fix for fetch joins with scalar selects

---

integration/hibernate-base/src/main/java/com/blazebit/persistence/impl/hibernate/HibernateJpaProvider.java

The trivial fix for #521. Surprisingly the reproducer #522 failed to address this issue. I am still working on a true reproducer.

Use getSubclassTableSpan instead of getTableSpan, fixes #521

---

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java
core/impl/src/main/java/com/blazebit/persistence/impl/SelectManager.java
core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TupleTest.java

Defer instantiation of TupleObjectBuilder to properly initialise tuple element aliases.
#490

Defer instantiation of TupleObjectBuilder to properly initialise tuple element aliases

---

integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/annotation/OptionalParam.java
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/AbstractPartTreeBlazePersistenceQuery.java
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/JpaParameters.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentRepositoryTest.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/repository/DocumentRepository.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/view/DocumentView.java

- Add `OptionalParam` annotation to denote parameters to be bound via `EntityViewSetting::addOptionalParameter`
- ~~Add also support for `Specification` parameters~~
Partly fixes #325.
Provides ability to customize `EntityViewSetting` via Spring repository interfaces.

[#325] Add support for EntityViewSetting parameters

---

integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/AbstractPartTreeBlazePersistenceQuery.java
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/JpaParameters.java

Omit the `sort` param on count query creation, which is irrelevant and might cause exceptions.
Fixes #617

[#617] Omit the sort param during count query creation

---

documentation/src/main/asciidoc/entity-view/manual/en_US/04_mappings.adoc

Remove unnecessary `@EntityViewInheritanceMapping` annotation from `CatView` and `DogView` in [§3.17.2. Inheritance mapping and JPA inheritance](https://persistence.blazebit.com/documentation/1.3/entity-view/manual/en_US/#inheritance-mapping-and-jpa-inheritance).

Remove unnecessary annotation

---

integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/AbstractPartTreeBlazePersistenceQuery.java
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/JpaParameters.java
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/repository/EntityViewSettingProcessor.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentRepositoryTest.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/repository/DocumentRepository.java

Adds `EntityViewSettingProcessor` interface which can be used as a parameter of Spring Data repository to customize the `EntityViewSetting` during the query creation.
Fixes #622

[#622] Add support for EntityViewSetting in Spring

---

integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/AbstractPartTreeBlazePersistenceQuery.java

This let methods like
```
FooView findOne(Specification<Foo> spec, @OptionalParam("foo") String foo);
```
to be handled by `AbstractPartTreeBlazePersistenceQuery`, which otherwise would throw a `No property findOne found for type Foo` exception.

Add One suffix to method name pattern

---

core/impl/src/main/java/com/blazebit/persistence/impl/EmbeddableSplittingVisitor.java
core/impl/src/main/java/com/blazebit/persistence/impl/FunctionalDependencyAnalyzerVisitor.java
core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedTypedQueryImpl.java
core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationEmbeddedIdTest.java

[#711] Test and fix for wrong pagination for partly constantified embedded id pagination

---

integration/spring-data/2.1/src/main/java/com/blazebit/persistence/spring/data/impl/repository/BlazePersistenceRepositoryFactoryBean.java

Spring Boot 2.1.4 brings `spring-data-jpa` version 2.1.6 which fails at startup if the repository-factory bean lacks a setter for the property `escapeCharacter`.
This PR simply adds a no-op setter, since a real setter would require the updated dependency for the missing type `EscapeCharacter` to be set on the repository-factory, e.g.
```java
public void setEscapeCharacter(char escapeCharacter) {
EscapeCharacter ec = EscapeCharacter.of(escapeCharacter);
respositoryFactory.setEscapeCharacter(ec);
}
```
The no-op setter fixes Spring Boot 2.1.4+ apps from throwing on startup.

Support spring-data-jpa 2.1.6

---

README.md
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/EntityViewSortUtil.java
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/query/AbstractPartTreeBlazePersistenceQuery.java
integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/AbstractEntityViewAwareRepository.java
integration/spring-data/base/src/main/java/org/springframework/data/jpa/repository/query/FixedJpaQueryCreator.java
integration/spring-data/testsuite/pom.xml
integration/spring-data/testsuite/src/main/java/com/blazebit/persistence/spring/data/testsuite/entity/Person.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/DocumentRepositoryTest.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/repository/DocumentRepository.java
integration/spring-data/testsuite/src/test/java/com/blazebit/persistence/spring/data/testsuite/view/DocumentView.java

This adds support for entity-view property sorting via Spring `Sort`: it checks if `Sort` contains properties which are sortable via entity-view sorters, if so it creates a `Sorter` and apply it to the view setting; it also replace the original `Sort` with a new one without the sorting which has been delegated to the view setting.
This is applied both to `AbstractEntityViewAwareRepository` and `AbstractPartTreeBlazePersistenceQuery` to support both concrete and derived methods.
This allows sorting by entity-view properties without the need of explicitly create and add `Sorter`s to the entity-view setting.

Add support for view property sorting with Spring Sort

---

core/parser/src/main/java/com/blazebit/persistence/parser/expression/AbstractCachingExpressionFactory.java
core/parser/src/main/java/com/blazebit/persistence/parser/expression/AbstractExpressionFactory.java
core/parser/src/main/java/com/blazebit/persistence/parser/expression/ConcurrentHashMapExpressionCache.java
core/parser/src/main/java/com/blazebit/persistence/parser/expression/ExpressionCache.java
core/parser/src/main/java/com/blazebit/persistence/parser/expression/JPQLNextExpressionVisitorImpl.java
entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/PrefixingQueryGenerator.java
entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/AbstractAttribute.java
entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java
entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/AbstractCorrelationJoinTupleElementMapper.java
entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/mapper/TupleElementMapperBuilder.java
entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/inheritance/polymorphic/model/SingleTableBaseView.java

[#857] Fix some regressions in JPQLNext parser

---

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ViewMappingImpl.java

`MappedSuperclassType` is an `IdentifiableType` but could also be an embeddable, so it's not always necessary for its views to have an `@IdMapping`.

Exclude MappedSuperclassType from IdMapping checks

---

core/api/src/main/java/com/blazebit/persistence/FromBaseBuilder.java

As I understand the API these methods should use entityClass as parameter name.

Use entityClass in fromEntitySubquery methods as parameter name

---

core/testsuite/pom.xml
entity-view/testsuite/pom.xml
integration/datanucleus-5.1/pom.xml
integration/datanucleus/pom.xml
integration/deltaspike-data/testsuite/pom.xml
integration/hibernate-6.0/pom.xml
integration/spring-data/2.0/pom.xml
integration/spring-data/2.1/pom.xml
integration/spring-data/2.2/pom.xml
integration/spring-data/testsuite/pom.xml
jpa-criteria/testsuite/pom.xml
pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

documentation/src/main/asciidoc/entity-view/manual/en_US/updatable_entity_views.adoc

Fixes a documentation typo in `@UpdatableEntityView` code example. `@MappingUpdatable` doesn't exists. The correct name is `@UpdatableMapping`

docs: fixes a typo in `@UpdatableEntityView` example

---

examples/quarkus/testsuite/base/src/test/resources/application.properties
examples/quarkus/testsuite/native/h2/src/main/resources/application.properties
examples/quarkus/testsuite/native/mssql/src/main/resources/application.properties
examples/quarkus/testsuite/native/mysql/src/main/resources/application.properties
examples/quarkus/testsuite/native/postgresql/src/main/resources/application.properties
testsuite-base/jpa/src/main/java/com/blazebit/persistence/testsuite/base/jpa/SchemaClearer.java

The new configuration was introduced in 1.3 and the old one deprecated.
We recently removed the support for the old configuration in master.

Move to the new Quarkus datasource configuration

---

integration/spring-data/webmvc/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/json/EntityViewAwareMappingJackson2HttpMessageConverter.java

Use the `Getter` instead of direct field access - the field has been renamed to `defaultObjectMapper` in `2.4.3`
Relates to #1266
Add support for Spring Boot 2.4.3

Add support for spring boot 2.4.3 - fix objectMapper field access - fixes #1266

---

CHANGELOG.md
core/api/src/main/java/com/blazebit/persistence/spi/CriteriaBuilderConfigurationContributor.java
core/api/src/main/java/com/blazebit/persistence/spi/Priority.java
core/impl/src/main/java/com/blazebit/persistence/impl/CriteriaBuilderConfigurationImpl.java
core/impl/src/main/java/com/blazebit/persistence/impl/util/CriteriaBuilderConfigurationContributorComparator.java
core/impl/src/test/java/com/blazebit/persistence/impl/util/CriteriaBuilderConfigurationContributorComparatorTest.java
core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/CustomFunctionTest.java
documentation/src/main/asciidoc/core/manual/en_US/configuration.adoc
integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/AbstractHibernateEntityManagerFactoryIntegrator.java

Allow third-party integrations to extend the CriteriaBuilderConfiguration through a Service Provider interface.
Fixes #1072
The https://github.com/jwgmeligmeyling/hibernate-types-querydsl-apt project provides an extension for working with custom types in special dialects. For this purpose, some additional functions need to be registered with Hibernate, however, Blaze-Persistence needs to be aware which functions are aggregate functions (for implicit group by) and which ones are not. Therefore the functions need to be registered as Blaze-Persistence functions as well. A service provider interface allows third party libraries like mine to provide the required configuration within the library itself.

[#1072] Introduce CriteriaBuilderConfigurationContributor

---

integration/quarkus/runtime/src/main/resources/META-INF/quarkus-extension.yaml
parent/pom.xml

https://github.com/Blazebit/blaze-persistence/pull/1415 is the way to go for the future but Blaze Persistence still supports JDK 8 for now, which makes it a bit impractical.
So for now, we just update the metadata to a format that should work with latest Quarkus.
It should be tested by going to the Dev UI of a 2.6.1.Final project and make sure the BP tile is there.

[#1414] Fix Quarkus extension metadata take 2

---

CHANGELOG.md
core/testsuite/src/test/hibernate/com/blazebit/persistence/testsuite/Issue1436Test.java
integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java

[#1436] Fix boot issue when model contains an association to an entity type that has an id class

---

integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java
integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java

The `SerializerBase` which the `JPQLNextSerializer` is based on maintains a mapping of constants to unique parameter names. This ensures for each unique object (by identity) only a single parameter name is introduced. Because this mapping is shared between the main query and subqueries, a query with parameters in both a subquery and the outer query, where the subquery is rendered in the select clause, results in a raise condition where the parameters for the outer query are set when serializing the subquery.
There are a few options to fix this:
1. Only bind parameters that are managed in the `ParameterManager` for the active builder.
2. Only render parameters and constants for the main query, after all subqueries have already been rendered
3. Use a stack based constant to parameter …

[#1453] Fix rendering parameters in subqueries in select clause

---

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java
core/impl/src/main/java/com/blazebit/persistence/impl/AbstractFullQueryBuilder.java
core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java
integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/AbstractBlazeJPAQuery.java
integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java
integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java
integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java

Render default joins with no alias (Blaze-Persistence will generate it under the hood). Previously the default alias was used which may result into alias conflicts.
Fixes #1458

[#1458] Fix rendering of association joins without alias

---

examples/it-service-management/pom.xml
examples/spring-data-dgs/pom.xml
examples/spring-data-graphql/pom.xml
examples/spring-data-spqr/pom.xml
integration/graphql-spqr/pom.xml
parent/pom.xml

Since 2.4 the starter no longer includes junit-vintage-engine
for junit 4 tests so it has to be included explicitly.

stop ignoring tests in newer versions of spring-boot-starter-test

---

CHANGELOG.md
examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/fetcher/CatGraphQLApi.java
integration/graphql-dgs/src/test/java/com/blazebit/persistence/integration/graphql/dgs/SampleTest.java
integration/graphql-dgs/src/test/java/com/blazebit/persistence/integration/graphql/dgs/fetcher/CatGraphQLApi.java
integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupportFactory.java

Beforehand, we created a specific type `ViewNode` for the connection.edge.node type, which was a clone of the actual `View` that was to be returned. With this PR this is changed, by default, the actual `View` is used as an connection.edge.node type.
See #1719 for more information.
You can activate the old bahavior by setting `GraphQLEntityViewSupportFactory.setCreateNodeViewTypeForEdge(true)`
Misc:
- Also reproduces the `__typename` issue in #1707 (for DGS)
Fixes #1707. Fixes #1719

Use basic view as Node type for as an connection.edge.node type by default fixes #1707 #1719

---

integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java
integration/graphql/src/test/java/com/blazebit/persistence/integration/graphql/TestSchemaHelpers.java

By turning this flag on users are able avoid silent surprises in the "fetches" 
which otherwise are hard to detect (typically everything "works" but the SQL
query is suboptimal).

[#1707] GraphQLEntityViewSupport: introduce and use strictFieldMappingCheck flag

---

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java

Just removed a second call to `applyJpaLimit` which seems to unnecessarily add a second time the "LIMIT x" to the query
https://github.com/Blazebit/blaze-persistence/issues/1756
This bug makes it impossible to use LIMIT in a lateral query

[1756] Remove second call to applyJpaLimit when building lateral query

---

CHANGELOG.md
build.sh
core/impl/src/main/java/com/blazebit/persistence/impl/ConstantifiedJoinNodeAttributeCollector.java
core/impl/src/main/java/com/blazebit/persistence/impl/ExpressionUtils.java
core/impl/src/main/java/com/blazebit/persistence/impl/OrderByManager.java
entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/pagination/PaginationTest.java

[#1803] Fix NPE caused by wrong order by expression during criteria builder copying

---

CHANGELOG.md

Fixing missing GQL extended types changelog notes

Fix 1.6.11 release notes

---

integration/spring-data/webmvc-jakarta/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/BlazePersistenceWebConfiguration.java
integration/spring-data/webmvc-jakarta/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/json/EntityViewAwareMappingJackson2HttpMessageConverter.java
integration/spring-data/webmvc/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/BlazePersistenceWebConfiguration.java
integration/spring-data/webmvc/src/main/java/com/blazebit/persistence/spring/data/webmvc/impl/json/EntityViewAwareMappingJackson2HttpMessageConverter.java

The `EntityViewAwareMappingJackson2HttpMessageConverter` now uses the `ObjectMapper` provided by the Spring Boot context. This ensures that users' custom configurations are used.
Fixes #1858
This change allows users to use custom deserializers and other `ObjectMapper` configurations with Blaze Persistence Entity Views.

[#1858] Fix EntityViewAwareMappingJackson2HttpMessageConverter to use Spring Boot's ObjectMapper

---

documentation/src/main/asciidoc/core/manual/en_US/cte.adoc
documentation/src/main/asciidoc/core/manual/en_US/querydsl.adoc

Fix the issues mentioned at https://github.com/Blazebit/blaze-persistence/issues/1943#issuecomment-2437827939
That's, the recursive table  is referenced twice, and the absolute path issue.

fix: Minor errors in the documentation

---

integration/hibernate6-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/HibernateJpaProvider.java

Small hotfix for #1886
https://github.com/Blazebit/blaze-persistence/issues/1886
Currently HibernateJpaProvider throws ArrayIndexOutOfBoundsException for ElementCollection of Embeddables having Embeddable. This small hotfix fixes this issue. Otherwise it doesn't work on quarkus 3+

Fix HibernateJpaProvider

---

integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java

A NullPointerExceptions is thrown when a view type is not mapped for a requested GraphQL type.
#1973
See #1973

[#1973] Properly handle unmapped view types in GraphQLEntityViewSupport

---

entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilder.java
entity-view/testsuite/src/test/java/com/blazebit/persistence/view/testsuite/basic/InheritanceFetchesTest.java

Adapted `ViewTypeObjectBuilder` to fetch discriminator column instead of selecting `NULL` when inheritance and `public <X> SubGraph<X> fetch(String path)` are in use.
#1522 
I encountered a similar issue at my company, though it wasn’t directly related to GraphQL. The problem occurred with certain `public <X> SubGraph<X> fetch(String path)` calls of `EntityViewSetting<T, Q extends FullQueryBuilder<T, Q>>` for inheritance queries. From what I understand of the codebase, this mechanism is also involved in the GraphQL query flow.
Because I approached the issue from a slightly different angle, I’m not entirely certain this fix resolves every aspect of the GraphQL case, but based on my tests, I believe it should help. 
This is my first time contributing to Blaze-Persistence, so I’m not …

[#1522] Unable to make a paginated query (GraphQl) for an entity view with inheritance configured

---

CONTRIBUTING.md
core/impl/src/main/java/com/blazebit/persistence/impl/PaginatedCriteriaBuilderImpl.java
core/testsuite/src/test/java/com/blazebit/persistence/testsuite/PaginationTest.java

Changed response type for getIdQuery from `TypedQuery<Object[]>` to `TypedQuery<Object>` to avoid doubly listing the ID parameters
#2002
Solves getting paginated results on jakarta 3.x with inline ID query disabled

#2002 Play nice with jakarta 3.x and disabled inline id queries

---

examples/pom.xml
examples/quarkus-3/pom.xml
integration/pom.xml
integration/quarkus-3/deployment/pom.xml
integration/quarkus-3/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceCdiProcessor.java
integration/quarkus-3/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceInstanceDescriptorBuildItem.java
integration/quarkus-3/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java
integration/quarkus-3/pom.xml
integration/quarkus-3/runtime/pom.xml
integration/quarkus-3/runtime/src/main/java/com/blazebit/persistence/integration/quarkus/runtime/BlazePersistenceConfiguration.java
integration/quarkus-3/runtime/src/main/java/com/blazebit/persistence/integration/quarkus/runtime/BlazePersistenceInstanceConfiguration.java
integration/quarkus-3/runtime/src/main/java/com/blazebit/persistence/integration/quarkus/runtime/EntityViewRecorder.java
parent/pom.xml

Update Quarkus to 3.8 as the minimum version and switch to the new `@ConfigMapping` infrastructure.
#1998 
At some point in the future, we will retire the legacy config classes so let's migrate to the new @ConfigMapping infrastructure.
I was conservative and only updated to Quarkus 3.8.
Note that there might be more optimizations possible with having all elements in a single map but I tried to be as less intrusive as possible as I don't know the codebase.

[#1998] Upgrade to Quarkus 3.8 and switch to `@ConfigMapping`

---

core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java
core/impl/src/main/java/com/blazebit/persistence/impl/CTEManager.java
core/testsuite/src/main/java/com/blazebit/persistence/testsuite/AbstractCoreTest.java
core/testsuite/src/test/java/com/blazebit/persistence/testsuite/QueryBuilderCopyTest.java

Build CTE Key using copied join manager instead of original so that the CTE can be found during selection.
Fixes #2014
See ticket above

[#2014] Copying criteria builder with CTE throws exception

---

core/impl/src/main/java/com/blazebit/persistence/impl/keyset/LazyKeysetLink.java
core/impl/src/test/java/com/blazebit/persistence/impl/keyset/LazyKeysetLinkTest.java

LazyKeysetLink#initialize now uses the loops actual orderByExpression instead of reusing the first one over and over again.
#2042 
This change makes it possible to use the `afterKeyset().with("expression", "value")`, with multiple `with` statements. Before it would reuse the value of the first `with` expression for the whole keyset, this is now fixed.

[#2042] Fix LazyKeysetLink#initialize using the same orderByExpression in every loop iteration

---

CHANGELOG.md
integration/spring-data/1.x/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.0/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.1/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.2/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.3/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.4/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.5/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.6/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/2.7/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/3.1/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/3.3/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/3.4/src/main/java/com/blazebit/persistence/spring/data/impl/query/PartTreeBlazePersistenceQuery.java
integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/ParameterizedReadOnlyDocumentRepositoryTest.java
integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/accessor/DocumentAccessors.java
integration/spring-data/testsuite/webmvc/src/test/java/com/blazebit/persistence/spring/data/testsuite/webmvc/repository/ReadOnlyDocumentRepository.java

I added `Pageable.unpaged()` support for `SlicedExecution` objects. I also added tests covering return types such as `List` and `Slice`.
https://github.com/Blazebit/blaze-persistence/issues/1814
Adds a missing feature analogous to Spring Data JPA.

[#1814] Fixed Pageable.unpaged() in repository methods with Slice return type
